### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by brantje** [brantje/nextnote#17]
- [x] List notes
  - [x] Sort by name
  - [x] Sort by modified date
- [x] Create note
- [x] Edit note
- [x] Delete note
- [x] Auto save
- [x] List deleted notes
- [x] Rename namespace to nextnotes
- [x] Sharing of notes
- [ ] Groups
  - [x] Show groups
  - [x] Filter by group
  - [ ] Rename group
  - [ ] Delete group
- [ ] Select multiple notes to delete

API:
- [x] Filter by `deleted` or `grouping`
- [ ] Add note_type to so we know when we have markdown. Possible values: `html` / `markdown`

**Comment by ThomasDaheim** [comment]
Some more todos for us

- [ ] migration support from ownnote - avoid issues with tables already existing
- [ ] add support for folder storage

**Comment by enoch85** [comment]
@brantje What's up? Too much workload right now? Would love to see the stable version soon. :+1:

**Comment by brantje** [comment]
Closing, separate issues is the way to go.
