### ISSUE TITLE
Todo list backend update

### ISSUE THREAD

**Issue by brantje** [brantje/nextnote#68]
- [x] Rename nextnotes to nextnotes_notes
- [x] Make group references id based.
- [x] Include a `note_count` property in group api responses
- [ ] Update notes with a notebook_id instead of the notebook object.
